Repository protofire/maker-governance-dashboard, pull requests merged in 2019-12, with the labels that each got.

#273 Executive Vote Details: Split graph "Number of Voters vs. Total MKR Staked"
  src/components/VoteDetails/Charts/VotersVsMkrChart.tsx
  src/components/VoteDetails/index.tsx
Labels: Epic

#274 Executive Vote Details: Make exec vote details show new data
  src/components/PollDetails/helpers.tsx
  src/components/VoteDetails/helpers.tsx
  src/utils/index.tsx
Labels: Epic

#271 Feedback M5 and M6
  src/components/Home/HomeDetail.tsx
  src/components/List/helpers.tsx
  src/components/PollDetails/Charts/PollPerOptionChart.tsx
  src/components/PollDetails/index.tsx
  src/components/common/Icon/hat.svg
  src/components/common/Table/index.tsx
  src/components/common/index.tsx
  src/components/common/styled/index.tsx
Labels: bug, enhancement

#275 Address navigation
  package-lock.json
  package.json
  src/components/Home/helpers.tsx
  src/components/List/helpers.tsx
  src/components/PollDetails/helpers.tsx
  src/components/VoteDetails/helpers.tsx
  src/components/common/AddressNav/index.tsx
  src/components/common/CopyToClipboard/index.tsx
  src/components/common/Icon/copy.svg
  src/components/common/Icon/external.svg
  src/components/common/Icon/index.tsx
  src/components/common/index.tsx
Labels: Epic

#284 Renamed exec vote details
  src/components/VoteDetails/helpers.tsx
Labels: bug

#272 Dashboard: Maker activeness breakdown
  src/components/Home/HomeDetail.tsx
  src/components/Home/helpers.tsx
  src/components/VoteDetails/Charts/ExecutiveVsHatChart.tsx
  src/components/VoteDetails/Charts/index.tsx
  src/components/VoteDetails/helpers.tsx
  src/components/VoteDetails/index.tsx
  src/containers/Vote/index.tsx
  src/containers/Vote/queries.tsx
  src/types/generatedGQL.ts
Labels: Epic

#287 Updated tile arrangement and some improvements
  src/components/Home/HomeDetail.tsx
  src/components/Home/helpers.tsx
Labels: enhancement

#289 Dashboard: Staked MKR Chart
  src/components/Home/Charts/StakedMkrChart.tsx
  src/components/Home/Charts/index.tsx
  src/components/Home/HomeDetail.tsx
  src/components/Home/helpers.tsx
  src/containers/Home/index.tsx
  src/containers/Home/queries.tsx
  src/containers/Vote/queries.tsx
  src/types/generatedGQL.ts
  src/utils/index.tsx
  src/utils/mkr-registry.ts
Labels: Epic

#296 Milestone 7 - Feedback
  src/components/Home/helpers.tsx
  src/components/PollDetails/Charts/TimeLeftChart.tsx
  src/components/PollDetails/Charts/index.tsx
  src/components/PollDetails/index.tsx
  src/components/VoteDetails/Charts/ExecutiveVsHatChart.tsx
  src/components/VoteDetails/helpers.tsx
  src/containers/Executive/queries.tsx
  src/containers/Polls/queries.tsx
  src/types/generatedGQL.ts
  src/utils/makerdao.ts
Labels: bug, enhancement

#301 M7 - Feedback v2
  src/components/Home/Charts/MKRActivenessChart.tsx
  src/components/Home/helpers.tsx
Labels: bug

#305 Fix mouse pointers on table
  src/components/Home/HomeDetail.tsx
  src/components/common/Table/index.tsx
Labels: bug

#307 Hide Breakdown Tile
  src/components/Home/HomeDetail.tsx
Labels: bug

#303 Fix activeness calculation
  src/components/Home/helpers.tsx
Labels: bug

#286 Voting History: Search voter by address
  src/components/VotingHistoryDetails/index.tsx
  src/components/common/Table/filters.tsx
  src/containers/App/index.tsx
  src/containers/VotingHistory/index.tsx
  src/containers/VotingHistory/queries.tsx
  src/types/generatedGQL.ts
Labels: Epic

#310 Revert 307 bugfix/hide breakdown
  src/components/Home/HomeDetail.tsx
  src/components/Home/helpers.tsx
  src/components/VotingHistoryDetails/index.tsx
  src/components/common/Table/filters.tsx
  src/containers/App/index.tsx
  src/containers/VotingHistory/index.tsx
  src/containers/VotingHistory/queries.tsx
  src/types/generatedGQL.ts
Labels: bug

#288 Voting History: Voting history list by address
  src/components/List/helpers.tsx
  src/containers/App/index.tsx
  src/containers/VoterHistory/index.tsx
  src/containers/VoterHistory/queries.tsx
  src/types/generatedGQL.ts
Labels: Epic

#312 Milestone 8 - Feedback
  netlify.toml
  package-lock.json
  package.json
  src/components/Home/HomeDetail.tsx
  src/components/Home/helpers.tsx
  src/components/PollDetails/Charts/PollPerOptionChart.tsx
  src/components/PollDetails/helpers.tsx
  src/components/PollDetails/index.tsx
  src/components/VoteDetails/Charts/ExecutiveVsHatChart.tsx
  src/components/VoteDetails/helpers.tsx
  src/components/VoteDetails/index.tsx
  src/components/VotingHistoryDetails/index.tsx
  src/components/common/AddressNav/index.tsx
  src/components/common/Chart/index.tsx
  src/components/common/styled/index.tsx
  src/containers/VotingHistory/queries.tsx
  src/index.tsx
  src/types/generatedGQL.ts
Labels: bug
