Repository protofire/maker-governance-dashboard, pull requests merged in 2019-11, with the labels that each got.

#211 Fixed date with current poll
  src/components/PollDetails/helpers.tsx
Labels: bug

#213 Renamed existing tiles
  src/components/Home/HomeDetail.tsx
  src/components/PollDetails/index.tsx
  src/components/VoteDetails/Charts/ApprovalsByAddressChart.tsx
  src/components/VoteDetails/index.tsx
Labels: Epic

#217 Made description text fit on poll and Executive vote details page
  package-lock.json
  src/components/VoteDetails/index.tsx
  src/components/common/styled/index.tsx
Labels: enhancement

#224 Added list separators
  src/components/List/helpers.tsx
  src/components/common/Table/index.tsx
Labels: enhancement

#227 Set active hat in Executive list
  src/components/List/helpers.tsx
  src/components/common/Icon/hat.svg
  src/components/common/Icon/index.tsx
  src/components/common/Table/index.tsx
  src/containers/Executive/index.tsx
  src/containers/Executive/queries.tsx
  src/types/generatedGQL.ts
Labels: enhancement

#237 Organized tiles
  src/components/Home/HomeDetail.tsx
  src/components/common/index.tsx
  src/components/common/styled/index.tsx
  src/containers/Home/index.tsx
Labels: Epic

#239 Do not query if addresses is empty
  src/components/PollDetails/data.ts
Labels: bug

#228 Fixed charts domain in poll details page
  src/components/PollDetails/Charts/MakerDistributionChart.tsx
  src/components/PollDetails/data.ts
  src/components/PollDetails/helpers.tsx
Labels: bug

#238 Uncasted executives
  src/components/Home/HomeDetail.tsx
  src/components/Home/helpers.tsx
Labels: Epic

#229 Most voted polls
  src/components/Home/HomeDetail.tsx
  src/components/Home/helpers.tsx
  src/components/List/helpers.tsx
  src/components/PollDetails/data.ts
  src/components/PollDetails/helpers.tsx
  src/components/common/Table/filters.tsx
  src/containers/Home/queries.tsx
  src/containers/Polls/index.tsx
  src/types/generatedGQL.ts
  src/utils/index.tsx
Labels: Epic

#241 Show/Hide data series and rescale charts
  src/components/Home/Charts/MkrDistributionPerExecutiveChart.tsx
  src/components/Home/Charts/VotersVsMkrChart.tsx
  src/components/PollDetails/Charts/MakerDistributionChart.tsx
  src/components/PollDetails/Charts/VotersDistributionChart.tsx
  src/components/common/Chart/index.tsx
  src/components/common/Icon/index.tsx
  src/components/common/index.tsx
  src/components/common/styled/index.tsx
Labels: Epic

#254 MKR staked polls
  src/components/Home/Charts/VotersVsMkrChart.tsx
  src/components/Home/HomeDetail.tsx
  src/components/List/helpers.tsx
  src/components/VoteDetails/Charts/VotersVsMkrChart.tsx
  src/components/VoteDetails/index.tsx
  src/containers/Polls/index.tsx
Labels: Epic

#255 Make poll details show new data
  src/components/PollDetails/helpers.tsx
  src/components/PollDetails/index.tsx
Labels: Epic

#256 Poll Details: Top voters
  src/components/PollDetails/data.ts
  src/components/PollDetails/helpers.tsx
  src/components/PollDetails/index.tsx
  src/utils/index.tsx
Labels: Epic

#258 Make total MKR balance request work with ad blockers
  .env.example
  netlify.toml
  src/components/PollDetails/Charts/PollPerOptionChart.tsx
  src/components/PollDetails/index.tsx
  src/utils/makerdao.ts
Labels: bug

#253 Dashboard: Top Voters
  src/components/Home/Charts/VotersVsMkrChart.tsx
  src/components/Home/HomeDetail.tsx
  src/components/Home/helpers.tsx
  src/containers/Home/index.tsx
  src/containers/Home/queries.tsx
  src/types/generatedGQL.ts
Labels: Epic

#265 Temporary fix in casted vote
  src/components/PollDetails/index.tsx
  src/containers/Executive/index.tsx
  src/containers/Vote/index.tsx
Labels: bug

#267 Dashboard: MKR Responsiveness
  src/components/Home/Charts/ExecutivesResponsivenessChart.tsx
  src/components/Home/Charts/PollsResponsivenessChart.tsx
  src/components/Home/Charts/index.tsx
  src/components/Home/HomeDetail.tsx
  src/components/Home/helpers.tsx
  src/components/common/Chart/index.tsx
  src/constants/index.tsx
  src/containers/Home/index.tsx
  src/containers/Home/queries.tsx
  src/types/generatedGQL.ts
  src/utils/index.tsx
Labels: Epic

#269 Removed harcoded value
  src/containers/Executive/index.tsx
  src/containers/Vote/index.tsx
Labels: bug

#268 Dashboard: MKR Activeness (30 Day Average)
  src/components/Home/Charts/MKRActivenessChart.tsx
  src/components/Home/Charts/index.tsx
  src/components/Home/HomeDetail.tsx
  src/components/Home/helpers.tsx
Labels: Epic
